### ISSUE TITLE
This repository is empty

### ISSUE THREAD

**Issue by Thor--** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#1]
Put up the source for this pls :D

**Comment by AndrewHeim** [comment]
Hi, Thor!

#WorkingOnIt

Do you have something specific you need them for on a timeline?  Otherwise it may take me a few days to a couple of weeks before it all gets up.

**Comment by Thor--** [comment]
No timeline or specific need, just was excited to see that the source for the steps might make it out!  It's just a solid example of a full-featured TestStand typepalette in general, and would be something great to point people to who are looking to start doing some hardcore TestStand customization.

**Comment by AndrewHeim** [comment]
Yup.  I have all the approvals needed to post it here.

I'll leave this issue open till the repository isn't empty anymore ;-)

**Comment by AndrewHeim** [comment]
Still empty.  Reopening issue!

**Comment by o-rhino** [comment]
Any plans to post the source? I've got an upcoming project where having access to the source for this would be helpful.

**Comment by AndrewHeim** [comment]
We've been updating this.  We hope to post the code publicly soon.  As always, please get in touch with us for any specific concerns.

**Comment by AndrewHeim** [comment]
Closed - addressed in 3fa877a
