### ISSUE TITLE
Passing an Array as Parameter to a TestStand Sequence

### ISSUE THREAD

**Issue by aegeeik** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#16]
When calling a TestStand sequence, only parameters of plain scalar types (boolean, DBL, U32 etc.) can be used. A sequence with an array as parameter (e.g. array of U32)  cannot be used.

**Comment by adchurch** [comment]
@aegeeik , I'm a little confused by this issue. Are you referring to VeriStand RT Sequence Parameters? A screenshot would be great.

**Comment by aegeeik** [comment]
Hi @adchurch, Thank you for waiting for my reply for such a long time.
Unfortunately I do not have the code in front of me anymore, therefore I cannot provide much helpful information anymore.
