### ISSUE TITLE
VeriStand.exe must be located on C: drive if using Windows 32-bit

### ISSUE THREAD

**Issue by adchurch** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#23]
If using Windows 32-bit then VeriStand must be installed to:

`C:\Program Files (x86)\National Instruments\NI VeriStand 201x`

in order for the Start VeriStand and Initialize VeriStand Steps to work.

**Comment by jifly4011510** [comment]
HI, I installed "ni-veristand-2017-steps-for-teststand_8.0.1+118_windows_x64" vipk package, my Veristand vision is 2017,my Teststand vision is 2017(32bit), the operating system is Win7 64bit and I installed Veristand in D:\Program Files (x86)\National Instruments\VeriStand 2017 。but I still encountered problems using initialize Veristand step in teststand, you can give me some suggestions?
![image](https://user-images.githubusercontent.com/45475359/49265953-3d417200-f48f-11e8-8665-70e207599400.png)

**Comment by adchurch** [comment]
This issue is caused by a hard-coded path for the VeriStand executable when using a 32-bit OS. 

![image](https://user-images.githubusercontent.com/8986632/49415843-89194300-f73d-11e8-9630-95453bc27d97.png)

I am removing this case structure entirely. VeriStand 2015 SP1 requires Windows 64-bit so therefore the VeriStand Steps for TestStand do too. 

![image](https://user-images.githubusercontent.com/8986632/49415938-de555480-f73d-11e8-92c2-8984032751cb.png)

VeriStand must still be installed to the default directory but can be installed on other drives now.

**Comment by adchurch** [comment]
@jifly4011510 it seems like your situation is different because you're using a 64-bit operating system. I'll create a separate issue for the problem you are seeing.

**Comment by jifly4011510** [comment]
@adchurch Thank you for your reply. I have reinstall my Veristand and located it into the default directory，and the problem has been solved. I will continue to focus on the new issue you created and hope it can be solved. THX.

**Comment by adchurch** [comment]
This is fixed in PR #32. See Issue #30 for details on the fix and the [VeriStand Steps Configuration File readme](https://github.com/NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand/wiki/VeriStand-Steps-Configuration-File-Instructions) for instructions on how to use a custom VeriStand installation path.
