### ISSUE TITLE
Parallel RT sequence Files

### ISSUE THREAD

**Issue by rdp137** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#28]
Am I able to use multiple "RT Sequence action" step calls running in parallel threads to run multiple RT sequences in Parallel.  It doesn't seem like I can.

**Comment by adchurch** [comment]
@rdp137 this should be possible using TestStand's built in parallel flow control features (Batch Process Model e.g.) or using the lower level RT Sequence/Stimulus Profile Step Types.

Take a look at the **NI VeriStand>>Advanced>>Low-Level Stimulus Profile Control>>Run Stimulus Profile (Asynch)** step type.
