### ISSUE TITLE
Cannot launch VeriStand from D: drive using Windows 64-bit

### ISSUE THREAD

**Issue by adchurch** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#30]
Reported by jifly4011510:

HI, I installed "ni-veristand-2017-steps-for-teststand_8.0.1+118_windows_x64" vipk package, my Veristand vision is 2017,my Teststand vision is 2017(32bit), the operating system is Win7 64bit and I installed Veristand in D:\Program Files (x86)\National Instruments\VeriStand 2017 。but I still encountered problems using initialize Veristand step in teststand, you can give me some suggestions?

![image](https://user-images.githubusercontent.com/8986632/49416535-deeeea80-f73f-11e8-9b25-2fc95497457e.png)

**Comment by Jaker20** [comment]
Hi,I have the same issues,you can give me some suggestions?

**Comment by Jaker20** [comment]
Hi,I have the same problem,you can give me some suggestions?
![image](https://user-images.githubusercontent.com/43367423/49509115-6c0c7d80-f8bf-11e8-9bec-6c97777c709a.png)

**Comment by Jaker20** [comment]
@adchurch  the OS using 46-bit,
I'm using the NI Package Maninstallation to installation
the primary system drive letter is C.

**Comment by adchurch** [comment]
Hi @Jaker20 , to be clear, your system drive is C: and NI VeriStand is installed on D: ?

**Comment by Jaker20** [comment]
Hi @adchurch the system drive is C,and NI VeriStand is installed on D.
the NI veristand need installed  on system drive?

**Comment by adchurch** [comment]
@Jaker20  we will have a fix for this in the next day or so.

**Comment by adchurch** [comment]
Version 8.1.0 of the step types will include support for a configuration file to override VeriStand's application installation path. 

![ni-veristand-steps-configuration-file](https://user-images.githubusercontent.com/8986632/50183093-b8e84f00-02d6-11e9-8788-7489baae5a7c.png)

Both the *Initialize VeriStand* and *Start VeriStand* step types will search for the **ni-veristand-steps-configuration.conf** INI file when trying to launch VeriStand. If the **veristand_application_path** key is found under the **[paths]** section then this path will be used to launch VeriStand instead of the default installation path. 

![startveristand_refactor_top](https://user-images.githubusercontent.com/8986632/50183233-1086ba80-02d7-11e9-8c63-7d143b0cfd94.png)
![startveristand_get_default_app_path](https://user-images.githubusercontent.com/8986632/50183240-12e91480-02d7-11e9-9598-db87eea9f0c1.png)
![startveristand_search_for_conf_file](https://user-images.githubusercontent.com/8986632/50183243-15e40500-02d7-11e9-952f-da6aa0f62fcf.png)

The steps should now return a useful error if there is an error launching the VeriStand executable. 
![startveristand_error](https://user-images.githubusercontent.com/8986632/50183263-26947b00-02d7-11e9-92eb-e74148b16893.png)

**Comment by adchurch** [comment]
Fixed in PR #32
