### ISSUE TITLE
TestStand Execution stuck at VeriStand step

### ISSUE THREAD

**Issue by bayaskarnr** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#31]
Hi, 
I am using TestStand 2017 and VeriStand 2017 for test execution. I am using VeriStand Test Ad-dons from site _https://forums.ni.com/t5/NI-VeriStand-Add-Ons-Documents/NI-VeriStand-Add-on-VeriStand-Steps-for-TestStand/ta-p/3535888_

I am facing issue in test script execution that test execution stuck at randomly at any set or get 
VeriStand step and i have to terminate execution. As per my observation this issue is is for the script which have more than 20 mins execution time.

**Comment by adchurch** [comment]
Hi @bayaskarnr, can you confirm the exact version of the VeriStand Steps for TestStand you are using? 

The forum page you linked is no longer updated. The latest versions of the VeriStand Step Types can be found on the GitHub page here:

 https://github.com/NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand/releases

Does the script get stuck at a different Step each time?

**Comment by adchurch** [comment]
Hey @bayaskarnr, let me know if you're still observing this issue, otherwise I'm going to mark this Issue closed. Thanks!

**Comment by bayaskarnr** [comment]
Hey,
 This issue is revolved after upgrading latest version. Thanks for support.
