### ISSUE TITLE
Issues with initialize veristand in teststand

### ISSUE THREAD

**Issue by vijayjayaramm007** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#34]
I have Veristand 2017 and Teststand 2017 in my pc.I also installed ni veristand steps for teststand 2017 version.If i open initialize veristand in teststand it shows following error.I need a solutions for this problem.

Thanks in advance.

![error](https://user-images.githubusercontent.com/46337263/50624277-76fd1100-0f44-11e9-9d00-0bab2f62b0c7.png)

**Comment by adchurch** [comment]
Hi @vijayjayaramm007, I'm having trouble reproducing this here. Can you confirm the version of the VeriStand Steps for TestStand you have installed? You can check this through NI Package Manager for versions 8.0.0+ or through the TestStand Types Palette window (Cntrl+T) for all versions.

Did you have any previous versions of the VeriStand Steps installed?

**Comment by vijayjayaramm007** [comment]
Hi @adchurch Thanks for the Reply.
I have installed the version 8.1.0 in my pc and also uninstalled previous version of veristand steps.

**Comment by adchurch** [comment]
Hi @vijayjayaramm007, can you confirm the contents of this directory on the PC? 

![image](https://user-images.githubusercontent.com/8986632/50780435-86dc6400-1268-11e9-9e14-d678ede20f3a.png)

Is this the only PC where the problem happens or the only PC you have tried etc?

**Comment by vijayjayaramm007** [comment]
@adchurch 
I have only pc installed with Teststand and Veristand.

I have attached the details below.
[TypePalettes.zip](https://github.com/NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand/files/2736750/TypePalettes.zip)

**Comment by mbilyk** [comment]
Can you please post the exact version you are using? This will look like 8.1.0+113 or something like that. Also please confirm that the version of LabVIEW Runtime you are using is 17.0.1f3. You can do this in NI MAX.
Are you using TestStand 64bit or 32bit?
What troubleshooting steps have you tried so far?

**Comment by rajasekharn42** [comment]
![image](https://user-images.githubusercontent.com/49761676/56405270-39b95680-6289-11e9-84ca-9ec2e4fd12c0.png)

I'm unable to start Veristand from TestStand. I have installed ni-veristand-2018-steps-for-teststand_8.1.0+116_windows_x64, TestStand 2017 (32bit & 64bit) & Veristand 2018. The TypePalettes folder has only MyTypes config file. I added ni-veristand-steps-configuration.conf & set the path to point to the Veristand.exe directory. It seems like TestStand is unable to locate the lvlibp needed for Initialization. Can u help me fix this issue? I tried uninstalling & reinstalling this add on several times.

**Comment by mbilyk** [comment]
@rajasekharn42,

Please post a new issue and include the steps you are taking to install the steps. These are the steps from the readme, it sounds like you may be performing extra steps.

1. Download the .nipkg file from the Releases page of this repository
2. Locate the .nipkg file on your local drive
3. Install the .nipkg file by double-clicking the file

**Comment by mbilyk** [comment]
Have not heard back from the original poster
