### ISSUE TITLE
Retunval is empty

### ISSUE THREAD

**Issue by PaoloPereira** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#36]
I've installed the last package (8.1.0)and ran the example seq. Everything works well except that the returnval container is empty when calling RT seqence Get Rise Time.
On the last page of the document "Training - Engine Veristand training Demo", it shows how to display the Rise time. In my case it is always 0. The seq is correctly executed, I even tried to write a constant value different from 0 in the .nivsseq, but the step still reports 0 in Returnval.
 The "ReportText" it's printed in the report but by default it is not activated.
Is there a missing step in the tutorial? If I add it in the "Additional Results" I only see an empty string.

**Comment by mbilyk** [comment]
@PaoloPereira, the issue looks like its related to the fact that RunRTSequenceAction does not return any values. I working on a fix that should be up soon. In the meantime, changing it to a RunRTSequenceNumericLimit should act as a workaround.

**Comment by PaoloPereira** [comment]
@mbilyk, it works much better now. Just as a note, the property Returnval don't seems to exist, so I pointed out to Step.Result.Numeric

**Comment by mbilyk** [comment]
@PaoloPereira 
Can you test the latest release to make sure it fixes this issue?
