### ISSUE TITLE
@rajasekharn42,

### ISSUE THREAD

**Issue by rajasekharn42** [NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand#44]
I downloaded the ni-veristand-2018-steps-for-teststand_8.1.0+116 pkg and installed it on my pc. Since I faced the error of launching VeriStand, I followed this additional step as mentioned in link https://github.com/NIVeriStandAdd-Ons/VeriStand-steps-for-TestStand/wiki/VeriStand-Steps-Configuration-File-Instructions. Then only I found that .lvlibp is missing after installation. I tried uninstalling & re-installing again several times, but it didn't help me. 
Toolchain on my PC : TestStand 2017 (32bit&64bit), Veristand 2018, LabVIEW 2018. OS: Windows 7
![image](https://user-images.githubusercontent.com/49761676/56433580-e974df80-62ee-11e9-913d-c77032cbe470.png)
On another PC running Windows 10, I'm facing the same issue & couldn't even uninstall this add-on from package manager. 
 **Error -125440 : An error occurred while running the custom execute queue 'pre**'.

**Comment by mbilyk** [comment]
@rajasekharn42,

I appreciate you giving some further context on the instructions you used.

Can you walk me through the steps you took to install the tools? I just tried installing them on a Windows 10 system with VeriStand 2018 and TestStand 2017 64bit and there was no issue with the installation. I don't expect there to be a problem with Windows 7, but these are not specifically tested on that OS.

**Comment by rajasekharn42** [comment]
TypePalettes folder has only MyTypes config file after installation. I couldn't see those lvlibp and Veristand icon in my directory post installation of package. Will patching the file contents of Veristand 2018 steps directory help me resolve the issue? Also help me in resolving this error on my Win 10 PC Error -125440 : An error occurred while running the custom execute queue 'pre'.

**Comment by rajasekharn42** [comment]
I downloaded the pkg & ran it which opened up in NI package manager. Accepting license agreements....the installation was smooth & there was no error during installation. I even re-installed TestStand 2017 32bit & nipkg after facing this issue.

**Comment by mbilyk** [comment]
If the installation is not occurring correctly, that is probably the reason for the error.

Here is what my C:\Users\Public\Documents\National Instruments\TestStand 2017 (64-bit)\Components\TypePalettes folder looks like
![image](https://user-images.githubusercontent.com/33259264/56438284-05a15e00-62a8-11e9-933a-23bdd26de836.png)

The ultimate thing that needs to happen is for those two files to be present in that folder. But the package also does things like register the correct dlls in the GAC. I'm not certain it will work just by placing those files in the correct directory.

Can you find the steps in NI Package Manager?
![image](https://user-images.githubusercontent.com/33259264/56439110-9aa55680-62aa-11e9-9e1b-019f96adc9ed.png)

**Comment by mbilyk** [comment]
Send me an image of what it looks like in package manager, I meant to say.
